import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const user = await prisma.user.findUnique({
    where: { email: "lampscycot@gmail.com" },
  });
  if (!user) {
    console.error(
      "Platemate-användaren hittades inte. Skapa användaren med e-post lampscycot@gmail.com först."
    );
    process.exit(1);
  }

  console.log(`Skapar recept för användare: ${user.email}`);

  const recipes = [
    // SVENSKA
    {
      title: "Klassiska köttbullar",
      description: "Mormors köttbullar med krämig gräddsås, lingon och mjölig potatis.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 30,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Blandfärs", amount: 500, unit: "g", order: 0 },
        { name: "Ströbröd", amount: 3, unit: "msk", order: 1 },
        { name: "Mjölk", amount: 1, unit: "dl", order: 2 },
        { name: "Ägg", amount: 1, unit: "styck", order: 3 },
        { name: "Gul lök", amount: 1, unit: "styck", order: 4 },
        { name: "Salt", amount: 1, unit: "tsk", order: 5 },
        { name: "Svartpeppar", amount: 0.5, unit: "tsk", order: 6 },
        { name: "Smör", amount: 50, unit: "g", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Blöt ströbrödet i mjölken i 5 minuter.", duration: 5 },
        { order: 1, instruction: "Finhacka löken och fräs mjuk i lite smör. Låt svalna.", duration: 5 },
        {
          order: 2,
          instruction: "Blanda färs, ägg, blött ströbröd, lök, salt och peppar. Arbeta ihop till en smidig smet.",
          duration: 5,
        },
        { order: 3, instruction: "Rulla till jämna bollar, ungefär valnötsstora.", duration: 10 },
        {
          order: 4,
          instruction:
            "Stek köttbullarna i smör på medelvärme tills de är genomstekta och fått fin färg, ca 8–10 minuter.",
          duration: 10,
        },
      ],
    },
    {
      title: "Svenska pannkakor",
      description: "Tunna och spröda pannkakor serverade med sylt och grädde.",
      category: "frukost",
      difficulty: "easy",
      servings: 4,
      prepTime: 10,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 3, unit: "dl", order: 0 },
        { name: "Ägg", amount: 3, unit: "styck", order: 1 },
        { name: "Mjölk", amount: 6, unit: "dl", order: 2 },
        { name: "Salt", amount: 0.5, unit: "tsk", order: 3 },
        { name: "Smör", amount: 50, unit: "g", order: 4 },
      ],
      steps: [
        { order: 0, instruction: "Vispa ihop mjöl och ägg till en slät smet.", duration: 3 },
        { order: 1, instruction: "Tillsätt mjölk lite i taget och vispa tills smeten är slät. Salta.", duration: 3 },
        { order: 2, instruction: "Låt smeten vila i 30 minuter.", duration: 30 },
        { order: 3, instruction: "Stek tunna pannkakor i smör på hög värme tills de är gyllenbruna.", duration: 15 },
      ],
    },
    {
      title: "Pytt i panna",
      description: "Klassisk svensk pytt med potatis, korv och lök. Servera med stekt ägg och rödbetor.",
      category: "middag",
      difficulty: "easy",
      servings: 4,
      prepTime: 15,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Kokt potatis", amount: 800, unit: "g", order: 0 },
        { name: "Falukorv", amount: 400, unit: "g", order: 1 },
        { name: "Gul lök", amount: 2, unit: "st", order: 2 },
        { name: "Smör", amount: 50, unit: "g", order: 3 },
        { name: "Salt", amount: 1, unit: "tsk", order: 4 },
        { name: "Svartpeppar", amount: 0.5, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Skär potatis och korv i tärningar, finhacka löken.", duration: 10 },
        { order: 1, instruction: "Stek löken mjuk i smör i en stor stekpanna.", duration: 5 },
        {
          order: 2,
          instruction: "Tillsätt potatis och korv. Stek på hög värme tills allt fått fin färg.",
          duration: 15,
        },
        { order: 3, instruction: "Salta och peppra. Servera med stekt ägg och inlagda rödbetor.", duration: 5 },
      ],
    },
    {
      title: "Janssons frestelse",
      description: "Krämig ugnsrätt med potatis, ansjovis och lök. En klassiker på julbordet.",
      category: "middag",
      difficulty: "easy",
      servings: 6,
      prepTime: 20,
      cookTime: 45,
      visibility: "public",
      ingredients: [
        { name: "Potatis", amount: 1000, unit: "g", order: 0 },
        { name: "Gul lök", amount: 3, unit: "st", order: 1 },
        { name: "Ansjovisfilé", amount: 100, unit: "g", order: 2 },
        { name: "Vispgrädde", amount: 3, unit: "dl", order: 3 },
        { name: "Ströbröd", amount: 2, unit: "msk", order: 4 },
        { name: "Smör", amount: 30, unit: "g", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Värm ugnen till 200°C. Skala och skär potatisen i tunna stavar.", duration: 10 },
        { order: 1, instruction: "Skiva löken och fräs mjuk i smör.", duration: 5 },
        { order: 2, instruction: "Varva potatis, lök och ansjovis i en smord ugnsform.", duration: 5 },
        { order: 3, instruction: "Häll grädde över, strö på ströbröd och lägg smörklickar på toppen.", duration: 3 },
        { order: 4, instruction: "Grädda i 45 minuter tills potatisen är mjuk och ytan gyllenbrun.", duration: 45 },
      ],
    },
    {
      title: "Ärtsoppa med fläsk",
      description: "Traditionell svensk torsdagsmat med gula ärtor och rimmat fläsk.",
      category: "lunch",
      difficulty: "easy",
      servings: 6,
      prepTime: 10,
      cookTime: 90,
      visibility: "public",
      ingredients: [
        { name: "Torkade gula ärtor", amount: 500, unit: "g", order: 0 },
        { name: "Rimmat sidfläsk", amount: 400, unit: "g", order: 1 },
        { name: "Gul lök", amount: 1, unit: "st", order: 2 },
        { name: "Vatten", amount: 2, unit: "l", order: 3 },
        { name: "Salt", amount: 1, unit: "tsk", order: 4 },
        { name: "Timjan", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Blötlägg ärtorna i vatten över natten.", duration: 0 },
        {
          order: 1,
          instruction: "Häll av blötläggningsvattnet. Koka ärtorna i nytt vatten med fläsk och lök.",
          duration: 90,
        },
        { order: 2, instruction: "Skumma av under kokningen. Salta och krydda med timjan.", duration: 5 },
        { order: 3, instruction: "Ta upp fläsket, skär i skivor och servera vid sidan av soppan.", duration: 5 },
      ],
    },
    {
      title: "Smörgåstårta",
      description: "Festlig smörgåstårta med räkor, ägg och lax. Perfekt till midsommar.",
      category: "lunch",
      difficulty: "medium",
      servings: 8,
      prepTime: 60,
      cookTime: 0,
      visibility: "public",
      ingredients: [
        { name: "Formbröd", amount: 12, unit: "st", order: 0 },
        { name: "Räkor", amount: 300, unit: "g", order: 1 },
        { name: "Rökt lax", amount: 200, unit: "g", order: 2 },
        { name: "Hårdkokta ägg", amount: 4, unit: "st", order: 3 },
        { name: "Majonnäs", amount: 3, unit: "dl", order: 4 },
        { name: "Crème fraiche", amount: 2, unit: "dl", order: 5 },
        { name: "Gurka", amount: 1, unit: "st", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Blanda majonnäs och crème fraiche till frosting.", duration: 5 },
        { order: 1, instruction: "Lägg ut bröd som botten, bred på fyllning med räkor och ägg.", duration: 15 },
        { order: 2, instruction: "Fortsätt varva bröd och fyllning, avsluta med bröd.", duration: 10 },
        {
          order: 3,
          instruction: "Bred frosting runt hela tårtan och dekorera med lax, räkor och gurka.",
          duration: 20,
        },
        { order: 4, instruction: "Ställ kallt minst 2 timmar innan servering.", duration: 120 },
      ],
    },
    {
      title: "Kladdkaka",
      description: "Svensk chokladkladdkaka med knaprig yta och seg mitt. En favorit på fikabordet.",
      category: "bakning",
      difficulty: "easy",
      servings: 8,
      prepTime: 10,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Smör", amount: 100, unit: "g", order: 0 },
        { name: "Ägg", amount: 2, unit: "st", order: 1 },
        { name: "Socker", amount: 2, unit: "dl", order: 2 },
        { name: "Kakao", amount: 4, unit: "msk", order: 3 },
        { name: "Vetemjöl", amount: 1, unit: "dl", order: 4 },
        { name: "Vaniljsocker", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Värm ugnen till 175°C. Smöra och bröa en springform.", duration: 5 },
        { order: 1, instruction: "Smält smöret. Vispa ihop ägg och socker.", duration: 5 },
        { order: 2, instruction: "Blanda i smält smör, kakao, mjöl och vaniljsocker.", duration: 3 },
        {
          order: 3,
          instruction: "Häll smeten i formen och grädda 12–15 minuter. Kakan ska vara kladdig i mitten.",
          duration: 15,
        },
      ],
    },
    {
      title: "Dillkött",
      description: "Kokt kalvkött i krämig dilsås. En söndagsklassiker.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 15,
      cookTime: 60,
      visibility: "public",
      ingredients: [
        { name: "Kalvkött", amount: 800, unit: "g", order: 0 },
        { name: "Lök", amount: 1, unit: "st", order: 1 },
        { name: "Morötter", amount: 2, unit: "st", order: 2 },
        { name: "Dill", amount: 1, unit: "dl", order: 3 },
        { name: "Smör", amount: 50, unit: "g", order: 4 },
        { name: "Vetemjöl", amount: 3, unit: "msk", order: 5 },
        { name: "Buljong", amount: 5, unit: "dl", order: 6 },
        { name: "Grädde", amount: 1, unit: "dl", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Koka köttet med lök och morötter i saltat vatten ca 45 minuter.", duration: 45 },
        { order: 1, instruction: "Ta upp köttet. Sila och spara buljongen.", duration: 5 },
        { order: 2, instruction: "Gör en redning av smör och mjöl, späd med buljong.", duration: 10 },
        { order: 3, instruction: "Tillsätt grädde och dill. Lägg tillbaka köttet i såsen.", duration: 5 },
      ],
    },
    {
      title: "Kanelbullar",
      description: "Saftiga svenska kanelbullar med kardemumma i degen.",
      category: "bakning",
      difficulty: "medium",
      servings: 20,
      prepTime: 30,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 8, unit: "dl", order: 0 },
        { name: "Mjölk", amount: 3, unit: "dl", order: 1 },
        { name: "Jäst", amount: 50, unit: "g", order: 2 },
        { name: "Smör", amount: 100, unit: "g", order: 3 },
        { name: "Socker", amount: 1, unit: "dl", order: 4 },
        { name: "Kardemumma", amount: 1, unit: "tsk", order: 5 },
        { name: "Kanel", amount: 2, unit: "msk", order: 6 },
        { name: "Pärlsocker", amount: 2, unit: "msk", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Värm mjölken till 37°C, lös upp jästen.", duration: 5 },
        {
          order: 1,
          instruction: "Blanda mjöl, socker, kardemumma och smör. Tillsätt mjölk och jäst. Knåda degen smidig.",
          duration: 15,
        },
        { order: 2, instruction: "Låt degen jäsa under duk i 30 minuter.", duration: 30 },
        {
          order: 3,
          instruction: "Kavla ut degen, bred på smör och kanel. Rulla ihop och skär i skivor.",
          duration: 15,
        },
        { order: 4, instruction: "Lägg på plåt, jäs 20 minuter. Pensla med ägg och strö pärlsocker.", duration: 20 },
        { order: 5, instruction: "Grädda i 225°C i 8–10 minuter.", duration: 10 },
      ],
    },
    {
      title: "Raggmunk med fläsk",
      description: "Krispiga potatisplättar med stekt rimmat fläsk och lingon.",
      category: "middag",
      difficulty: "easy",
      servings: 4,
      prepTime: 20,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Potatis", amount: 800, unit: "g", order: 0 },
        { name: "Ägg", amount: 2, unit: "st", order: 1 },
        { name: "Vetemjöl", amount: 2, unit: "msk", order: 2 },
        { name: "Mjölk", amount: 1, unit: "dl", order: 3 },
        { name: "Rimmat fläsk", amount: 300, unit: "g", order: 4 },
        { name: "Salt", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Riv potatisen grovt och pressa ur vätskan.", duration: 10 },
        { order: 1, instruction: "Blanda potatis med ägg, mjöl, mjölk och salt.", duration: 5 },
        { order: 2, instruction: "Stek fläsket krispigt i en torr panna.", duration: 10 },
        {
          order: 3,
          instruction: "Stek raggmunkarna i smör på medelvärme tills de är gyllenbruna på båda sidor.",
          duration: 15,
        },
      ],
    },

    // ITALIENSKA
    {
      title: "Pasta Carbonara",
      description: "Autentisk romersk carbonara med guanciale, ägg och pecorino. Ingen grädde!",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 10,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Spaghetti", amount: 400, unit: "g", order: 0 },
        { name: "Guanciale eller pancetta", amount: 150, unit: "g", order: 1 },
        { name: "Ägg", amount: 3, unit: "st", order: 2 },
        { name: "Äggula", amount: 2, unit: "st", order: 3 },
        { name: "Pecorino Romano", amount: 100, unit: "g", order: 4 },
        { name: "Svartpeppar", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Koka pastan al dente i saltat vatten. Spara 1 dl pastavätska.", duration: 10 },
        { order: 1, instruction: "Stek guancialen krispig på medelvärme.", duration: 8 },
        { order: 2, instruction: "Vispa ihop ägg, äggulor och riven pecorino. Peppra rikligt.", duration: 3 },
        { order: 3, instruction: "Ta pannan från värmen. Blanda pasta med guanciale.", duration: 2 },
        {
          order: 4,
          instruction: "Tillsätt äggsåsen och rör snabbt. Späd med pastavätska tills krämig konsistens.",
          duration: 3,
        },
      ],
    },
    {
      title: "Risotto ai funghi",
      description: "Krämig svamprisotto med porcini och parmesan.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 15,
      cookTime: 30,
      visibility: "public",
      ingredients: [
        { name: "Arborio-ris", amount: 300, unit: "g", order: 0 },
        { name: "Torkad porcini", amount: 30, unit: "g", order: 1 },
        { name: "Färska champinjoner", amount: 200, unit: "g", order: 2 },
        { name: "Vitt vin", amount: 1, unit: "dl", order: 3 },
        { name: "Kycklingbuljong", amount: 1, unit: "l", order: 4 },
        { name: "Parmesan", amount: 80, unit: "g", order: 5 },
        { name: "Smör", amount: 50, unit: "g", order: 6 },
        { name: "Schalottenlök", amount: 2, unit: "st", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Blötlägg porcini i varmt vatten 20 minuter. Sila och spara vätskan.", duration: 20 },
        { order: 1, instruction: "Fräs schalottenlök i smör. Tillsätt ris och rosta lätt.", duration: 5 },
        { order: 2, instruction: "Häll i vinet och rör tills det absorberas.", duration: 3 },
        { order: 3, instruction: "Tillsätt buljong en slev i taget under konstant omrörning.", duration: 20 },
        { order: 4, instruction: "Rör in svamp, porcinivatten, smör och parmesan. Vila 2 minuter.", duration: 5 },
      ],
    },
    {
      title: "Pizza Margherita",
      description: "Napolitansk pizza med San Marzano-tomater, mozzarella och färsk basilika.",
      category: "middag",
      difficulty: "medium",
      servings: 2,
      prepTime: 30,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 300, unit: "g", order: 0 },
        { name: "Vatten", amount: 2, unit: "dl", order: 1 },
        { name: "Jäst", amount: 5, unit: "g", order: 2 },
        { name: "Salt", amount: 1, unit: "tsk", order: 3 },
        { name: "San Marzano-tomater", amount: 200, unit: "g", order: 4 },
        { name: "Mozzarella", amount: 150, unit: "g", order: 5 },
        { name: "Färsk basilika", amount: 10, unit: "g", order: 6 },
        { name: "Olivolja", amount: 2, unit: "msk", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Blanda mjöl, vatten, jäst och salt. Knåda 10 minuter. Jäs 2 timmar.", duration: 130 },
        { order: 1, instruction: "Värm ugnen till max temperatur med en pizzasten eller plåt inne.", duration: 30 },
        { order: 2, instruction: "Kavla ut degen tunt. Bred på krossade tomater.", duration: 5 },
        { order: 3, instruction: "Lägg på mozzarella och ringla olivolja.", duration: 3 },
        { order: 4, instruction: "Grädda 8–12 minuter tills kanterna är bruna. Toppa med basilika.", duration: 10 },
      ],
    },
    {
      title: "Ossobuco alla Milanese",
      description: "Långkokt kalvlägg med gremolata och saffransrisotto.",
      category: "middag",
      difficulty: "hard",
      servings: 4,
      prepTime: 20,
      cookTime: 120,
      visibility: "public",
      ingredients: [
        { name: "Kalvlägg", amount: 4, unit: "st", order: 0 },
        { name: "Gul lök", amount: 2, unit: "st", order: 1 },
        { name: "Morötter", amount: 2, unit: "st", order: 2 },
        { name: "Selleri", amount: 2, unit: "st", order: 3 },
        { name: "Vitt vin", amount: 2, unit: "dl", order: 4 },
        { name: "Krossade tomater", amount: 400, unit: "g", order: 5 },
        { name: "Kycklingbuljong", amount: 3, unit: "dl", order: 6 },
        { name: "Citronskal", amount: 1, unit: "st", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Mjöla och bryn kalvläggen på hög värme.", duration: 10 },
        { order: 1, instruction: "Fräs lök, morötter och selleri mjuka.", duration: 8 },
        { order: 2, instruction: "Häll i vin och låt reducera.", duration: 5 },
        { order: 3, instruction: "Tillsätt tomater och buljong. Lägg tillbaka köttet.", duration: 5 },
        { order: 4, instruction: "Sjud på låg värme under lock i 1,5–2 timmar.", duration: 90 },
        {
          order: 5,
          instruction: "Gör gremolata av citronskal, vitlök och persilja. Strö över vid servering.",
          duration: 5,
        },
      ],
    },
    {
      title: "Tiramisù",
      description: "Klassisk italiensk dessert med mascarpone, espresso och amaretto.",
      category: "dessert",
      difficulty: "medium",
      servings: 8,
      prepTime: 30,
      cookTime: 0,
      visibility: "public",
      ingredients: [
        { name: "Mascarpone", amount: 500, unit: "g", order: 0 },
        { name: "Äggulor", amount: 4, unit: "st", order: 1 },
        { name: "Socker", amount: 1, unit: "dl", order: 2 },
        { name: "Vispgrädde", amount: 2, unit: "dl", order: 3 },
        { name: "Espresso", amount: 3, unit: "dl", order: 4 },
        { name: "Amaretto", amount: 2, unit: "msk", order: 5 },
        { name: "Savoiardi-kex", amount: 200, unit: "g", order: 6 },
        { name: "Kakao", amount: 2, unit: "msk", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Vispa äggulor och socker vitt och poröst.", duration: 5 },
        { order: 1, instruction: "Rör ner mascarpone i äggsmeten.", duration: 3 },
        { order: 2, instruction: "Vispa grädden lös och vänd ner i mascarponeblandningen.", duration: 5 },
        { order: 3, instruction: "Blanda espresso och amaretto. Doppa kexen snabbt.", duration: 5 },
        { order: 4, instruction: "Varva kex och kräm i en form. Avsluta med kräm.", duration: 10 },
        { order: 5, instruction: "Sikta kakao över. Ställ kallt minst 4 timmar.", duration: 240 },
      ],
    },
    {
      title: "Pappa al Pomodoro",
      description: "Toskansk tomatsoppa med gammalt bröd, olivolja och basilika.",
      category: "lunch",
      difficulty: "easy",
      servings: 4,
      prepTime: 10,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Gammalt bröd", amount: 300, unit: "g", order: 0 },
        { name: "Krossade tomater", amount: 800, unit: "g", order: 1 },
        { name: "Vitlök", amount: 3, unit: "st", order: 2 },
        { name: "Olivolja", amount: 4, unit: "msk", order: 3 },
        { name: "Basilika", amount: 20, unit: "g", order: 4 },
        { name: "Grönsaksbuljong", amount: 5, unit: "dl", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Fräs vitlök i olivolja tills gyllene.", duration: 3 },
        { order: 1, instruction: "Tillsätt tomater och buljong. Koka 15 minuter.", duration: 15 },
        { order: 2, instruction: "Smula ner brödet i soppan och rör om.", duration: 5 },
        { order: 3, instruction: "Koka ytterligare 5 minuter. Rör in basilika och olivolja.", duration: 5 },
      ],
    },
    {
      title: "Panna cotta",
      description: "Silkeslen italiensk desssert med vanilj och hallonsås.",
      category: "dessert",
      difficulty: "easy",
      servings: 6,
      prepTime: 15,
      cookTime: 5,
      visibility: "public",
      ingredients: [
        { name: "Vispgrädde", amount: 5, unit: "dl", order: 0 },
        { name: "Socker", amount: 0.5, unit: "dl", order: 1 },
        { name: "Vaniljstång", amount: 1, unit: "st", order: 2 },
        { name: "Gelatinblad", amount: 4, unit: "st", order: 3 },
        { name: "Frysta hallon", amount: 200, unit: "g", order: 4 },
      ],
      steps: [
        { order: 0, instruction: "Lägg gelatinbladen i kallt vatten i 5 minuter.", duration: 5 },
        { order: 1, instruction: "Koka upp grädde, socker och vanilj.", duration: 5 },
        { order: 2, instruction: "Krama ur gelatinet och lös upp i den varma grädden.", duration: 2 },
        { order: 3, instruction: "Häll i formar och ställ kallt i 4 timmar.", duration: 240 },
        { order: 4, instruction: "Koka hallon med socker till sås. Servera över panna cottan.", duration: 10 },
      ],
    },
    {
      title: "Focaccia",
      description: "Luftig italiensk focaccia med olivolja, rosmarin och flingsalt.",
      category: "bakning",
      difficulty: "easy",
      servings: 8,
      prepTime: 20,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 500, unit: "g", order: 0 },
        { name: "Vatten", amount: 3.5, unit: "dl", order: 1 },
        { name: "Jäst", amount: 10, unit: "g", order: 2 },
        { name: "Olivolja", amount: 6, unit: "msk", order: 3 },
        { name: "Flingsalt", amount: 1, unit: "tsk", order: 4 },
        { name: "Rosmarin", amount: 2, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Blanda mjöl, vatten, jäst och 3 msk olivolja. Knåda 8 minuter.", duration: 10 },
        { order: 1, instruction: "Jäs under duk i 1 timme.", duration: 60 },
        {
          order: 2,
          instruction: "Tryck ut degen i en olivoljad form. Tryck fördjupningar med fingrarna.",
          duration: 5,
        },
        { order: 3, instruction: "Ringla olivolja, strö rosmarin och flingsalt. Jäs 20 minuter.", duration: 20 },
        { order: 4, instruction: "Grädda i 220°C i 20–25 minuter.", duration: 25 },
      ],
    },
    {
      title: "Saltimbocca alla Romana",
      description: "Kalvschnitzel med prosciutto och salvia i vitt vinsås.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 15,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Kalvschnitzel", amount: 500, unit: "g", order: 0 },
        { name: "Prosciutto", amount: 8, unit: "st", order: 1 },
        { name: "Färsk salvia", amount: 16, unit: "st", order: 2 },
        { name: "Vitt vin", amount: 1, unit: "dl", order: 3 },
        { name: "Smör", amount: 50, unit: "g", order: 4 },
        { name: "Salt och peppar", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        {
          order: 0,
          instruction: "Lägg prosciutto och salviablad på varje schnitzel. Fäst med tandpetare.",
          duration: 10,
        },
        { order: 1, instruction: "Stek schnitzlarna med prosciuttosidan ner i smör 2–3 minuter.", duration: 5 },
        { order: 2, instruction: "Vänd och stek 1 minut. Ta upp och håll varma.", duration: 3 },
        { order: 3, instruction: "Häll vin i pannan och reducera till sås. Vispa in smör.", duration: 5 },
      ],
    },
    {
      title: "Minestrone",
      description: "Robust italiensk grönsakssoppa med pasta och parmesan.",
      category: "lunch",
      difficulty: "easy",
      servings: 6,
      prepTime: 20,
      cookTime: 35,
      visibility: "public",
      ingredients: [
        { name: "Zucchini", amount: 1, unit: "st", order: 0 },
        { name: "Morötter", amount: 2, unit: "st", order: 1 },
        { name: "Selleri", amount: 2, unit: "st", order: 2 },
        { name: "Krossade tomater", amount: 400, unit: "g", order: 3 },
        { name: "Vita bönor", amount: 400, unit: "g", order: 4 },
        { name: "Pasta", amount: 100, unit: "g", order: 5 },
        { name: "Grönsaksbuljong", amount: 1.5, unit: "l", order: 6 },
        { name: "Parmesan", amount: 50, unit: "g", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Fräs grönsaker i olivolja 5 minuter.", duration: 5 },
        { order: 1, instruction: "Tillsätt tomater och buljong. Koka 20 minuter.", duration: 20 },
        { order: 2, instruction: "Tillsätt bönor och pasta. Koka tills pastan är klar.", duration: 10 },
        { order: 3, instruction: "Servera med riven parmesan och olivolja.", duration: 2 },
      ],
    },

    // ASIATISKA
    {
      title: "Pad Thai",
      description: "Thailändsk woaad risnudlar med räkor, tofu och jordnötter.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 20,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Risnudlar", amount: 300, unit: "g", order: 0 },
        { name: "Räkor", amount: 200, unit: "g", order: 1 },
        { name: "Tofu", amount: 200, unit: "g", order: 2 },
        { name: "Ägg", amount: 2, unit: "st", order: 3 },
        { name: "Tamarindpasta", amount: 3, unit: "msk", order: 4 },
        { name: "Fisksås", amount: 2, unit: "msk", order: 5 },
        { name: "Socker", amount: 1, unit: "msk", order: 6 },
        { name: "Jordnötter", amount: 50, unit: "g", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Blötlägg nudlarna i kallt vatten 30 minuter.", duration: 30 },
        { order: 1, instruction: "Blanda tamarind, fisksås och socker till sås.", duration: 3 },
        { order: 2, instruction: "Woaa tofu krispig. Tillsätt räkor.", duration: 5 },
        { order: 3, instruction: "Skjut åt sidan, scramble äggen.", duration: 3 },
        { order: 4, instruction: "Tillsätt nudlar och sås. Woaa på hög värme.", duration: 5 },
        { order: 5, instruction: "Servera med jordnötter, lime och böngroddar.", duration: 2 },
      ],
    },
    {
      title: "Miso Ramen",
      description: "Japansk ramen med rik misobuljong, mjukkokat ägg och nori.",
      category: "middag",
      difficulty: "medium",
      servings: 2,
      prepTime: 20,
      cookTime: 30,
      visibility: "public",
      ingredients: [
        { name: "Ramen-nudlar", amount: 200, unit: "g", order: 0 },
        { name: "Vit miso", amount: 3, unit: "msk", order: 1 },
        { name: "Kycklingbuljong", amount: 8, unit: "dl", order: 2 },
        { name: "Ägg", amount: 2, unit: "st", order: 3 },
        { name: "Majskorn", amount: 1, unit: "dl", order: 4 },
        { name: "Nori", amount: 2, unit: "st", order: 5 },
        { name: "Salladslök", amount: 2, unit: "st", order: 6 },
        { name: "Sesamolja", amount: 1, unit: "tsk", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Koka äggen i 6 minuter för mjukkokta. Skala och halvera.", duration: 8 },
        { order: 1, instruction: "Koka upp buljongen. Vispa ner miso.", duration: 10 },
        { order: 2, instruction: "Koka nudlarna enligt förpackning.", duration: 5 },
        { order: 3, instruction: "Fördela nudlar i skålar. Häll misosoppa över.", duration: 3 },
        { order: 4, instruction: "Toppa med ägg, majs, nori och salladslök. Ringla sesamolja.", duration: 3 },
      ],
    },
    {
      title: "Vietnamesisk Phở",
      description: "Aromatisk nötköttsoppa med risnudlar, örter och lime.",
      category: "middag",
      difficulty: "hard",
      servings: 4,
      prepTime: 30,
      cookTime: 180,
      visibility: "public",
      ingredients: [
        { name: "Nötben", amount: 1000, unit: "g", order: 0 },
        { name: "Risnudlar", amount: 400, unit: "g", order: 1 },
        { name: "Ingefära", amount: 50, unit: "g", order: 2 },
        { name: "Lök", amount: 2, unit: "st", order: 3 },
        { name: "Stjärnanis", amount: 3, unit: "st", order: 4 },
        { name: "Fisksås", amount: 3, unit: "msk", order: 5 },
        { name: "Färsk koriander", amount: 30, unit: "g", order: 6 },
        { name: "Böngroddar", amount: 200, unit: "g", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Rosta lök och ingefära direkt på gasflamma tills brynt.", duration: 10 },
        { order: 1, instruction: "Koka benen med lök, ingefära och stjärnanis i 3 timmar.", duration: 180 },
        { order: 2, instruction: "Sila buljongen. Smaka av med fisksås.", duration: 10 },
        { order: 3, instruction: "Blötlägg nudlarna. Koka snabbt i kokande vatten.", duration: 5 },
        { order: 4, instruction: "Lägg nudlar i skålar, häll het buljong över. Toppa med örter.", duration: 5 },
      ],
    },
    {
      title: "Bibimbap",
      description: "Koreansk risrätt med grönsaker, nötkött och gochujangssås.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 30,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Jasminris", amount: 4, unit: "dl", order: 0 },
        { name: "Nötfärs", amount: 300, unit: "g", order: 1 },
        { name: "Spenat", amount: 200, unit: "g", order: 2 },
        { name: "Morot", amount: 2, unit: "st", order: 3 },
        { name: "Ägg", amount: 4, unit: "st", order: 4 },
        { name: "Gochujang", amount: 3, unit: "msk", order: 5 },
        { name: "Sesamolja", amount: 2, unit: "msk", order: 6 },
        { name: "Sojasås", amount: 2, unit: "msk", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Koka riset.", duration: 20 },
        { order: 1, instruction: "Stek nötfärsen med soja och sesamolja.", duration: 8 },
        { order: 2, instruction: "Woaa spenat och morot separat.", duration: 8 },
        { order: 3, instruction: "Stek äggen med rinnande gula.", duration: 3 },
        {
          order: 4,
          instruction: "Lägg ris i skål, arrangera grönsaker och kött runt. Toppa med ägg och gochujang.",
          duration: 5,
        },
      ],
    },
    {
      title: "Butter Chicken",
      description: "Indisk kycklingcurry i krämig tomatbaserad sås med massor av kryddor.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 20,
      cookTime: 40,
      visibility: "public",
      ingredients: [
        { name: "Kycklinglårfilé", amount: 700, unit: "g", order: 0 },
        { name: "Yoghurt", amount: 1, unit: "dl", order: 1 },
        { name: "Garam masala", amount: 2, unit: "tsk", order: 2 },
        { name: "Krossade tomater", amount: 400, unit: "g", order: 3 },
        { name: "Vispgrädde", amount: 2, unit: "dl", order: 4 },
        { name: "Smör", amount: 50, unit: "g", order: 5 },
        { name: "Ingefära", amount: 2, unit: "tsk", order: 6 },
        { name: "Vitlök", amount: 4, unit: "st", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Marinera kycklingen i yoghurt och garam masala i 1 timme.", duration: 60 },
        { order: 1, instruction: "Grilla eller stek kycklingen tills den är genomstekt.", duration: 15 },
        { order: 2, instruction: "Fräs vitlök och ingefära i smör.", duration: 3 },
        { order: 3, instruction: "Tillsätt tomater och koka 15 minuter.", duration: 15 },
        { order: 4, instruction: "Tillsätt grädde och kyckling. Sjud 10 minuter.", duration: 10 },
      ],
    },
    {
      title: "Gyoza",
      description: "Japanska dumplings fyllda med fläsk och kål, stekta och ångkokta.",
      category: "snacks",
      difficulty: "hard",
      servings: 4,
      prepTime: 60,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Gyozaskal", amount: 30, unit: "st", order: 0 },
        { name: "Fläskfärs", amount: 300, unit: "g", order: 1 },
        { name: "Kål", amount: 200, unit: "g", order: 2 },
        { name: "Ingefära", amount: 1, unit: "tsk", order: 3 },
        { name: "Sojasås", amount: 2, unit: "msk", order: 4 },
        { name: "Sesamolja", amount: 1, unit: "msk", order: 5 },
        { name: "Vitlök", amount: 2, unit: "st", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Finhacka kålen och salta. Pressa ut vätskan efter 10 minuter.", duration: 15 },
        { order: 1, instruction: "Blanda fläskfärs, kål, ingefära, vitlök, soja och sesamolja.", duration: 5 },
        { order: 2, instruction: "Lägg fyllning på varje skal. Vik och nyp ihop kanten.", duration: 30 },
        { order: 3, instruction: "Stek i olja tills undersidan är gyllenbrun, ca 2 minuter.", duration: 3 },
        { order: 4, instruction: "Tillsätt vatten, lägg på lock och ånga 5 minuter.", duration: 5 },
      ],
    },
    {
      title: "Tom Kha Gai",
      description: "Thailändsk kokosmjölkssoppa med kyckling, galangal och citrongräs.",
      category: "lunch",
      difficulty: "easy",
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Kycklingfilé", amount: 400, unit: "g", order: 0 },
        { name: "Kokosmjölk", amount: 400, unit: "ml", order: 1 },
        { name: "Kycklingbuljong", amount: 5, unit: "dl", order: 2 },
        { name: "Citrongräs", amount: 2, unit: "st", order: 3 },
        { name: "Galangal", amount: 30, unit: "g", order: 4 },
        { name: "Fisksås", amount: 2, unit: "msk", order: 5 },
        { name: "Lime", amount: 2, unit: "st", order: 6 },
        { name: "Koriander", amount: 20, unit: "g", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Krossa citrongräset och skiva galangal.", duration: 5 },
        { order: 1, instruction: "Koka buljong med citrongräs och galangal 10 minuter.", duration: 10 },
        { order: 2, instruction: "Tillsätt kokosmjölk och kyckling. Koka 10 minuter.", duration: 10 },
        { order: 3, instruction: "Smaka av med fisksås och limejuice. Toppa med koriander.", duration: 3 },
      ],
    },
    {
      title: "Japansk Cheesecake",
      description: "Luftig och len japansk cheesecake, mjukare än den västerländska varianten.",
      category: "dessert",
      difficulty: "hard",
      servings: 8,
      prepTime: 30,
      cookTime: 60,
      visibility: "public",
      ingredients: [
        { name: "Cream cheese", amount: 250, unit: "g", order: 0 },
        { name: "Smör", amount: 50, unit: "g", order: 1 },
        { name: "Mjölk", amount: 1, unit: "dl", order: 2 },
        { name: "Ägg", amount: 5, unit: "st", order: 3 },
        { name: "Socker", amount: 1, unit: "dl", order: 4 },
        { name: "Vetemjöl", amount: 60, unit: "g", order: 5 },
        { name: "Majsstärkelse", amount: 20, unit: "g", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Smält cream cheese, smör och mjölk i vattenbad.", duration: 10 },
        { order: 1, instruction: "Rör ner äggulor, mjöl och majsstärkelse.", duration: 5 },
        { order: 2, instruction: "Vispa äggvitorna med socker till styv maräng.", duration: 8 },
        { order: 3, instruction: "Vänd försiktigt ner marängen i ostmassan.", duration: 5 },
        { order: 4, instruction: "Grädda i vattenbad i 160°C i 60 minuter.", duration: 60 },
      ],
    },

    // MELLANÖSTERN
    {
      title: "Hummus",
      description: "Krämig hemgjord hummus med tahini, citron och olivolja.",
      category: "snacks",
      difficulty: "easy",
      servings: 6,
      prepTime: 10,
      cookTime: 0,
      visibility: "public",
      ingredients: [
        { name: "Kikärtor", amount: 400, unit: "g", order: 0 },
        { name: "Tahini", amount: 3, unit: "msk", order: 1 },
        { name: "Citron", amount: 1, unit: "st", order: 2 },
        { name: "Vitlök", amount: 2, unit: "st", order: 3 },
        { name: "Olivolja", amount: 3, unit: "msk", order: 4 },
        { name: "Spiskummin", amount: 0.5, unit: "tsk", order: 5 },
        { name: "Salt", amount: 1, unit: "tsk", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Häll av kikärtorna men spara lite av vätskan.", duration: 2 },
        { order: 1, instruction: "Mixa kikärtor, tahini, citronsaft, vitlök och olivolja.", duration: 3 },
        { order: 2, instruction: "Tillsätt lite kikärtsvatten för krämigare konsistens.", duration: 2 },
        {
          order: 3,
          instruction: "Smaka av med salt och spiskummin. Servera med olivolja och paprikapulver.",
          duration: 2,
        },
      ],
    },
    {
      title: "Falafel",
      description: "Krispig falafel av kikärtor med örter och kryddor.",
      category: "lunch",
      difficulty: "medium",
      servings: 4,
      prepTime: 20,
      cookTime: 15,
      visibility: "public",
      ingredients: [
        { name: "Torkade kikärtor", amount: 300, unit: "g", order: 0 },
        { name: "Persilja", amount: 30, unit: "g", order: 1 },
        { name: "Koriander", amount: 20, unit: "g", order: 2 },
        { name: "Vitlök", amount: 3, unit: "st", order: 3 },
        { name: "Lök", amount: 1, unit: "st", order: 4 },
        { name: "Spiskummin", amount: 1, unit: "tsk", order: 5 },
        { name: "Bakpulver", amount: 0.5, unit: "tsk", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Blötlägg kikärtor i kallt vatten över natten.", duration: 0 },
        { order: 1, instruction: "Mixa alla ingredienser grovt i matberedare. Salta.", duration: 5 },
        { order: 2, instruction: "Forma till bollar och kyl 30 minuter.", duration: 30 },
        { order: 3, instruction: "Fritera i 180°C olja tills gyllenbruna, ca 3–4 minuter.", duration: 10 },
      ],
    },
    {
      title: "Shawarma",
      description: "Mellanösternkryddad kyckling i tunnbröd med vitlökssås.",
      category: "lunch",
      difficulty: "medium",
      servings: 4,
      prepTime: 20,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Kycklinglår", amount: 700, unit: "g", order: 0 },
        { name: "Spiskummin", amount: 1, unit: "tsk", order: 1 },
        { name: "Koriander", amount: 1, unit: "tsk", order: 2 },
        { name: "Gurkmeja", amount: 0.5, unit: "tsk", order: 3 },
        { name: "Citron", amount: 1, unit: "st", order: 4 },
        { name: "Yoghurt", amount: 1, unit: "dl", order: 5 },
        { name: "Tunnbröd", amount: 4, unit: "st", order: 6 },
        { name: "Vitlök", amount: 3, unit: "st", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Marinera kycklingen med kryddor, citronsaft och olivolja i 1 timme.", duration: 60 },
        { order: 1, instruction: "Stek kycklingen tills genomstekt. Vila och skär i strimlor.", duration: 20 },
        { order: 2, instruction: "Blanda yoghurt med vitlök och salt till sås.", duration: 3 },
        { order: 3, instruction: "Fyll tunnbröd med kyckling, sallad och vitlökssås.", duration: 5 },
      ],
    },
    {
      title: "Tabouleh",
      description: "Frisk libanesisk bulgursallad med massor av persilja och mint.",
      category: "lunch",
      difficulty: "easy",
      servings: 4,
      prepTime: 20,
      cookTime: 0,
      visibility: "public",
      ingredients: [
        { name: "Bulgur", amount: 1, unit: "dl", order: 0 },
        { name: "Persilja", amount: 100, unit: "g", order: 1 },
        { name: "Mint", amount: 30, unit: "g", order: 2 },
        { name: "Tomater", amount: 3, unit: "st", order: 3 },
        { name: "Citron", amount: 2, unit: "st", order: 4 },
        { name: "Olivolja", amount: 3, unit: "msk", order: 5 },
        { name: "Salt", amount: 1, unit: "tsk", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Blötlägg bulgur i kokande vatten 10 minuter. Häll av och kyl.", duration: 15 },
        { order: 1, instruction: "Finhacka persilja, mint och tomater.", duration: 10 },
        { order: 2, instruction: "Blanda allt och krydda med citronsaft, olivolja och salt.", duration: 3 },
        { order: 3, instruction: "Låt stå 15 minuter för smakerna att gifta sig.", duration: 15 },
      ],
    },
    {
      title: "Shakshuka",
      description: "Ägg pocherade i kryddig tomatssås med paprika och harissa.",
      category: "frukost",
      difficulty: "easy",
      servings: 4,
      prepTime: 10,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Ägg", amount: 6, unit: "st", order: 0 },
        { name: "Krossade tomater", amount: 800, unit: "g", order: 1 },
        { name: "Röd paprika", amount: 2, unit: "st", order: 2 },
        { name: "Lök", amount: 1, unit: "st", order: 3 },
        { name: "Harissa", amount: 2, unit: "tsk", order: 4 },
        { name: "Spiskummin", amount: 1, unit: "tsk", order: 5 },
        { name: "Vitlök", amount: 3, unit: "st", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Fräs lök, paprika och vitlök mjuka i olivolja.", duration: 8 },
        { order: 1, instruction: "Tillsätt tomater, harissa och kryddor. Koka 10 minuter.", duration: 10 },
        { order: 2, instruction: "Gör fördjupningar i såsen och knäck ner äggen.", duration: 3 },
        { order: 3, instruction: "Lägg på lock och pochera äggen tills vitorna stelnat, ca 8 minuter.", duration: 8 },
      ],
    },
    {
      title: "Baba Ganoush",
      description: "Rökig auberginekräm med tahini och citron.",
      category: "snacks",
      difficulty: "easy",
      servings: 6,
      prepTime: 10,
      cookTime: 30,
      visibility: "public",
      ingredients: [
        { name: "Aubergine", amount: 2, unit: "st", order: 0 },
        { name: "Tahini", amount: 2, unit: "msk", order: 1 },
        { name: "Citron", amount: 1, unit: "st", order: 2 },
        { name: "Vitlök", amount: 2, unit: "st", order: 3 },
        { name: "Olivolja", amount: 2, unit: "msk", order: 4 },
        { name: "Salt", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        {
          order: 0,
          instruction: "Grilla auberginerna direkt på gasflamma eller i ugn tills skinnet är svart.",
          duration: 20,
        },
        { order: 1, instruction: "Låt svalna. Skrapa ur fruktköttet.", duration: 10 },
        { order: 2, instruction: "Mixa aubergine med tahini, vitlök och citronsaft.", duration: 3 },
        { order: 3, instruction: "Smaka av med salt. Ringla olivolja vid servering.", duration: 2 },
      ],
    },
    {
      title: "Marokkanskt lammtajine",
      description: "Långkokt lamm med aprikoser, mandlar och varma kryddor.",
      category: "middag",
      difficulty: "medium",
      servings: 6,
      prepTime: 20,
      cookTime: 120,
      visibility: "public",
      ingredients: [
        { name: "Lammkött", amount: 900, unit: "g", order: 0 },
        { name: "Torkade aprikoser", amount: 150, unit: "g", order: 1 },
        { name: "Mandlar", amount: 80, unit: "g", order: 2 },
        { name: "Lök", amount: 2, unit: "st", order: 3 },
        { name: "Ras el hanout", amount: 2, unit: "tsk", order: 4 },
        { name: "Kanel", amount: 1, unit: "tsk", order: 5 },
        { name: "Honung", amount: 2, unit: "msk", order: 6 },
        { name: "Kycklingbuljong", amount: 3, unit: "dl", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Bryn lammköttet i olivolja.", duration: 10 },
        { order: 1, instruction: "Fräs lök och kryddor.", duration: 5 },
        { order: 2, instruction: "Tillsätt buljong och aprikoser. Sjud på låg värme 1,5 timme.", duration: 90 },
        { order: 3, instruction: "Rör i honung och rosta mandlar. Strö över vid servering.", duration: 10 },
      ],
    },

    // MEXIKANSKA
    {
      title: "Tacos al Pastor",
      description: "Mexikanska tacos med marinerat fläsk, ananas och koriander.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 30,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Fläskfilé", amount: 600, unit: "g", order: 0 },
        { name: "Chipotle i adobo", amount: 2, unit: "msk", order: 1 },
        { name: "Ananas", amount: 200, unit: "g", order: 2 },
        { name: "Koriander", amount: 30, unit: "g", order: 3 },
        { name: "Maistortillas", amount: 8, unit: "st", order: 4 },
        { name: "Lök", amount: 1, unit: "st", order: 5 },
        { name: "Lime", amount: 2, unit: "st", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Marinera fläsket i chipotle, ananas och kryddor i 2 timmar.", duration: 120 },
        { order: 1, instruction: "Grilla eller stek fläsket på hög värme.", duration: 15 },
        { order: 2, instruction: "Vila köttet och skär i tunna skivor.", duration: 5 },
        { order: 3, instruction: "Servera i varma tortillas med lök, koriander och lime.", duration: 5 },
      ],
    },
    {
      title: "Guacamole",
      description: "Klassisk mexikansk guacamole med avokado, lime och jalapeño.",
      category: "snacks",
      difficulty: "easy",
      servings: 4,
      prepTime: 10,
      cookTime: 0,
      visibility: "public",
      ingredients: [
        { name: "Mogen avokado", amount: 3, unit: "st", order: 0 },
        { name: "Lime", amount: 2, unit: "st", order: 1 },
        { name: "Rödlök", amount: 0.5, unit: "st", order: 2 },
        { name: "Jalapeño", amount: 1, unit: "st", order: 3 },
        { name: "Koriander", amount: 20, unit: "g", order: 4 },
        { name: "Salt", amount: 1, unit: "tsk", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Mosa avokadon grovt med en gaffel.", duration: 3 },
        { order: 1, instruction: "Blanda i limejuice, finhackad rödlök och jalapeño.", duration: 3 },
        { order: 2, instruction: "Hacka koriander och rör ner.", duration: 2 },
        { order: 3, instruction: "Smaka av med salt. Servera direkt.", duration: 1 },
      ],
    },
    {
      title: "Enchiladas Verdes",
      description: "Mexikanska enchiladas med grön tomatillosås och kyckling.",
      category: "middag",
      difficulty: "medium",
      servings: 4,
      prepTime: 25,
      cookTime: 30,
      visibility: "public",
      ingredients: [
        { name: "Maistortillas", amount: 8, unit: "st", order: 0 },
        { name: "Kokt kyckling", amount: 400, unit: "g", order: 1 },
        { name: "Tomatillos", amount: 500, unit: "g", order: 2 },
        { name: "Jalapeño", amount: 2, unit: "st", order: 3 },
        { name: "Gräddfil", amount: 2, unit: "dl", order: 4 },
        { name: "Ost", amount: 150, unit: "g", order: 5 },
        { name: "Koriander", amount: 20, unit: "g", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Koka tomatillos och jalapeño. Mixa med koriander till salsa verde.", duration: 15 },
        { order: 1, instruction: "Riv kycklingen och blanda med lite sås.", duration: 5 },
        { order: 2, instruction: "Fyll tortillorna med kyckling, rulla och lägg i form.", duration: 10 },
        { order: 3, instruction: "Häll sås och gräddfil över. Strö ost på toppen.", duration: 3 },
        { order: 4, instruction: "Grädda i 200°C i 20 minuter.", duration: 20 },
      ],
    },
    {
      title: "Churros med chokladsås",
      description: "Friterade spanska-mexikanska bakverk med kanel och varm chokladsås.",
      category: "dessert",
      difficulty: "medium",
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 2, unit: "dl", order: 0 },
        { name: "Vatten", amount: 2, unit: "dl", order: 1 },
        { name: "Smör", amount: 50, unit: "g", order: 2 },
        { name: "Ägg", amount: 2, unit: "st", order: 3 },
        { name: "Socker", amount: 2, unit: "msk", order: 4 },
        { name: "Kanel", amount: 1, unit: "tsk", order: 5 },
        { name: "Mörk choklad", amount: 150, unit: "g", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Koka upp vatten och smör. Rör ner mjölet till en deg.", duration: 5 },
        { order: 1, instruction: "Låt svalna lite. Rör ner äggen ett i taget.", duration: 5 },
        { order: 2, instruction: "Spritsa långa remsor i het olja (180°C). Fritera gyllenbruna.", duration: 10 },
        { order: 3, instruction: "Rulla i kanel och socker.", duration: 3 },
        { order: 4, instruction: "Smält chokladen till dipsås. Servera direkt.", duration: 5 },
      ],
    },
    {
      title: "Pozole Rojo",
      description: "Mexikansk hominy-soppa med fläsk och röd chilesås.",
      category: "middag",
      difficulty: "medium",
      servings: 6,
      prepTime: 20,
      cookTime: 90,
      visibility: "public",
      ingredients: [
        { name: "Fläskkött", amount: 700, unit: "g", order: 0 },
        { name: "Hominy (konserverad)", amount: 800, unit: "g", order: 1 },
        { name: "Guajillo-chili", amount: 4, unit: "st", order: 2 },
        { name: "Ancho-chili", amount: 2, unit: "st", order: 3 },
        { name: "Vitlök", amount: 4, unit: "st", order: 4 },
        { name: "Lök", amount: 2, unit: "st", order: 5 },
        { name: "Oregano", amount: 1, unit: "tsk", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Koka fläskköttet med lök och vitlök i 1 timme.", duration: 60 },
        { order: 1, instruction: "Rosta och blötlägg chilifrukterna. Mixa med lite buljong.", duration: 20 },
        { order: 2, instruction: "Sila chilisåsen och rör ner i buljongen.", duration: 5 },
        { order: 3, instruction: "Tillsätt hominy och koka 30 minuter.", duration: 30 },
        { order: 4, instruction: "Servera med kål, lime, oregano och koriander.", duration: 5 },
      ],
    },

    // FRANSKA
    {
      title: "Crème Brûlée",
      description: "Klassisk fransk vaniljkräm med karamelliserat socker på toppen.",
      category: "dessert",
      difficulty: "medium",
      servings: 6,
      prepTime: 20,
      cookTime: 45,
      visibility: "public",
      ingredients: [
        { name: "Vispgrädde", amount: 5, unit: "dl", order: 0 },
        { name: "Äggulor", amount: 5, unit: "st", order: 1 },
        { name: "Socker", amount: 1, unit: "dl", order: 2 },
        { name: "Vaniljstång", amount: 1, unit: "st", order: 3 },
        { name: "Strösocker till karamell", amount: 4, unit: "msk", order: 4 },
      ],
      steps: [
        { order: 0, instruction: "Koka upp grädde med vanilj.", duration: 5 },
        { order: 1, instruction: "Vispa äggulor och socker. Häll varm grädde över under vispning.", duration: 5 },
        { order: 2, instruction: "Häll i formar och grädda i vattenbad i 150°C, 40 minuter.", duration: 45 },
        { order: 3, instruction: "Kyl helt. Strö socker och bränn med brylépistol.", duration: 5 },
      ],
    },
    {
      title: "Coq au Vin",
      description: "Klassisk fransk kyckling bräserad i rödvin med svamp och baconlardons.",
      category: "middag",
      difficulty: "hard",
      servings: 4,
      prepTime: 30,
      cookTime: 90,
      visibility: "public",
      ingredients: [
        { name: "Hel kyckling", amount: 1500, unit: "g", order: 0 },
        { name: "Rödvin", amount: 7, unit: "dl", order: 1 },
        { name: "Bacon", amount: 150, unit: "g", order: 2 },
        { name: "Champinjoner", amount: 300, unit: "g", order: 3 },
        { name: "Pärllök", amount: 200, unit: "g", order: 4 },
        { name: "Vitlök", amount: 4, unit: "st", order: 5 },
        { name: "Timjan", amount: 2, unit: "tsk", order: 6 },
        { name: "Kycklingbuljong", amount: 3, unit: "dl", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Dela kycklingen. Bryn i olja och reservera.", duration: 10 },
        { order: 1, instruction: "Stek bacon, pärllök och svamp.", duration: 8 },
        { order: 2, instruction: "Häll i vin och buljong. Lägg tillbaka kycklingen.", duration: 5 },
        { order: 3, instruction: "Sjud under lock i 1 timme tills kycklingen är mör.", duration: 60 },
        { order: 4, instruction: "Ta upp kycklingen. Reducera såsen och justera kryddningen.", duration: 15 },
      ],
    },
    {
      title: "Croissanter",
      description: "Smöriga franska croissanter med perfekt flagnig deg.",
      category: "bakning",
      difficulty: "hard",
      servings: 12,
      prepTime: 120,
      cookTime: 20,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 500, unit: "g", order: 0 },
        { name: "Smör", amount: 300, unit: "g", order: 1 },
        { name: "Mjölk", amount: 3, unit: "dl", order: 2 },
        { name: "Jäst", amount: 20, unit: "g", order: 3 },
        { name: "Socker", amount: 2, unit: "msk", order: 4 },
        { name: "Salt", amount: 1, unit: "tsk", order: 5 },
        { name: "Ägg", amount: 1, unit: "st", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Blanda deg av mjöl, mjölk, jäst, socker och salt. Kyl 1 timme.", duration: 70 },
        { order: 1, instruction: "Kavla ut degen. Lägg kallt smörblock i mitten och vik in.", duration: 15 },
        { order: 2, instruction: "Kavla och vik 4 gånger med 30 min vila i kyl emellan.", duration: 150 },
        { order: 3, instruction: "Kavla tunt, skär trianglar och rulla till croissanter.", duration: 20 },
        { order: 4, instruction: "Jäs 2 timmar. Pensla med ägg och grädda i 200°C i 18–20 min.", duration: 140 },
      ],
    },
    {
      title: "Soupe à l'oignon",
      description: "Fransk löksoppa med karamelliserad lök och gratinerat bröd.",
      category: "lunch",
      difficulty: "medium",
      servings: 4,
      prepTime: 10,
      cookTime: 60,
      visibility: "public",
      ingredients: [
        { name: "Gul lök", amount: 1000, unit: "g", order: 0 },
        { name: "Smör", amount: 50, unit: "g", order: 1 },
        { name: "Vitt vin", amount: 1, unit: "dl", order: 2 },
        { name: "Nötköttbuljong", amount: 1, unit: "l", order: 3 },
        { name: "Baguette", amount: 4, unit: "st", order: 4 },
        { name: "Gruyère", amount: 100, unit: "g", order: 5 },
        { name: "Timjan", amount: 2, unit: "tsk", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Skiva löken och karamellisera i smör på låg värme i 45 minuter.", duration: 45 },
        { order: 1, instruction: "Häll i vin och reducera. Tillsätt buljong och timjan.", duration: 5 },
        { order: 2, instruction: "Sjud 15 minuter. Smaka av.", duration: 15 },
        { order: 3, instruction: "Häll soppan i ugnssäkra skålar. Lägg bröd på toppen och strö ost.", duration: 5 },
        { order: 4, instruction: "Gratinera under grillen tills osten bubblar.", duration: 5 },
      ],
    },
    {
      title: "Bouillabaisse",
      description: "Provensalsk fiskgryta med saffran, fänkål och rouille.",
      category: "middag",
      difficulty: "hard",
      servings: 6,
      prepTime: 30,
      cookTime: 45,
      visibility: "public",
      ingredients: [
        { name: "Blandad fisk", amount: 1000, unit: "g", order: 0 },
        { name: "Räkor", amount: 300, unit: "g", order: 1 },
        { name: "Krossade tomater", amount: 400, unit: "g", order: 2 },
        { name: "Fänkål", amount: 1, unit: "st", order: 3 },
        { name: "Saffran", amount: 0.5, unit: "tsk", order: 4 },
        { name: "Fisksbuljong", amount: 1, unit: "l", order: 5 },
        { name: "Fänkålsfrön", amount: 1, unit: "tsk", order: 6 },
        { name: "Vitlök", amount: 4, unit: "st", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Fräs fänkål, vitlök och fänkålsfrön i olivolja.", duration: 8 },
        { order: 1, instruction: "Tillsätt tomater, buljong och saffran. Koka 20 minuter.", duration: 20 },
        { order: 2, instruction: "Tillsätt fast fisk. Koka 10 minuter.", duration: 10 },
        { order: 3, instruction: "Tillsätt räkor och mjuk fisk. Koka 5 minuter.", duration: 5 },
        { order: 4, instruction: "Servera med rouille och bröd.", duration: 3 },
      ],
    },

    // BAKNING OCH DESSERT
    {
      title: "Cinnamon Rolls",
      description: "Amerikanska kanelbullar med cream cheese-frosting.",
      category: "bakning",
      difficulty: "medium",
      servings: 12,
      prepTime: 40,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 600, unit: "g", order: 0 },
        { name: "Mjölk", amount: 3, unit: "dl", order: 1 },
        { name: "Jäst", amount: 25, unit: "g", order: 2 },
        { name: "Smör", amount: 100, unit: "g", order: 3 },
        { name: "Socker", amount: 1, unit: "dl", order: 4 },
        { name: "Kanel", amount: 3, unit: "msk", order: 5 },
        { name: "Cream cheese", amount: 200, unit: "g", order: 6 },
        { name: "Florsocker", amount: 2, unit: "dl", order: 7 },
      ],
      steps: [
        { order: 0, instruction: "Gör en mjuk deg av mjöl, mjölk, jäst, smör och socker. Jäs 1 timme.", duration: 70 },
        {
          order: 1,
          instruction: "Kavla ut degen till en rektangel. Bred smör och strö kanel och socker.",
          duration: 10,
        },
        { order: 2, instruction: "Rulla ihop och skär i 12 skivor. Lägg i form och jäs 30 minuter.", duration: 35 },
        { order: 3, instruction: "Grädda i 190°C i 20–25 minuter.", duration: 25 },
        {
          order: 4,
          instruction: "Blanda cream cheese och florsocker till frosting. Bred över varma bullar.",
          duration: 5,
        },
      ],
    },
    {
      title: "New York Cheesecake",
      description: "Tät och krämig cheesecake med digestivebotten och vanilj.",
      category: "dessert",
      difficulty: "medium",
      servings: 12,
      prepTime: 30,
      cookTime: 60,
      visibility: "public",
      ingredients: [
        { name: "Digestivekex", amount: 200, unit: "g", order: 0 },
        { name: "Smör", amount: 80, unit: "g", order: 1 },
        { name: "Cream cheese", amount: 700, unit: "g", order: 2 },
        { name: "Socker", amount: 2, unit: "dl", order: 3 },
        { name: "Ägg", amount: 3, unit: "st", order: 4 },
        { name: "Gräddfil", amount: 2, unit: "dl", order: 5 },
        { name: "Vaniljextrakt", amount: 1, unit: "tsk", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Krossa kexen och blanda med smält smör. Tryck ut i form.", duration: 10 },
        { order: 1, instruction: "Vispa cream cheese och socker. Tillsätt ägg ett i taget.", duration: 8 },
        { order: 2, instruction: "Rör ner gräddfil och vanilj.", duration: 3 },
        { order: 3, instruction: "Häll på bottnen. Grädda i 160°C i 55–60 minuter.", duration: 60 },
        { order: 4, instruction: "Stäng av ugnen och låt stå 1 timme. Kyl sedan i kyl.", duration: 60 },
      ],
    },
    {
      title: "Brownies",
      description: "Kladdiga chokladbrownies med valnötter och en perfekt knaprig yta.",
      category: "bakning",
      difficulty: "easy",
      servings: 16,
      prepTime: 15,
      cookTime: 25,
      visibility: "public",
      ingredients: [
        { name: "Mörk choklad", amount: 200, unit: "g", order: 0 },
        { name: "Smör", amount: 150, unit: "g", order: 1 },
        { name: "Socker", amount: 3, unit: "dl", order: 2 },
        { name: "Ägg", amount: 3, unit: "st", order: 3 },
        { name: "Vetemjöl", amount: 1.5, unit: "dl", order: 4 },
        { name: "Kakao", amount: 2, unit: "msk", order: 5 },
        { name: "Valnötter", amount: 100, unit: "g", order: 6 },
      ],
      steps: [
        { order: 0, instruction: "Värm ugnen till 175°C. Smelt choklad och smör.", duration: 5 },
        { order: 1, instruction: "Vispa ägg och socker vitt. Rör ner chokladsmöret.", duration: 5 },
        { order: 2, instruction: "Vänd ner mjöl, kakao och valnötter.", duration: 3 },
        { order: 3, instruction: "Häll i smord form och grädda 22–25 minuter. Mitten ska vara kladdig.", duration: 25 },
      ],
    },
    {
      title: "Lemon Curd Tart",
      description: "Fransk citrontart med len lemon curd och smördegsbotten.",
      category: "dessert",
      difficulty: "hard",
      servings: 8,
      prepTime: 40,
      cookTime: 30,
      visibility: "public",
      ingredients: [
        { name: "Vetemjöl", amount: 200, unit: "g", order: 0 },
        { name: "Smör", amount: 150, unit: "g", order: 1 },
        { name: "Citroner", amount: 4, unit: "st", order: 2 },
        { name: "Ägg", amount: 4, unit: "st", order: 3 },
        { name: "Socker", amount: 2, unit: "dl", order: 4 },
        { name: "Äggulor", amount: 2, unit: "st", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Gör smördeg av mjöl och smör. Kyl 30 minuter.", duration: 35 },
        { order: 1, instruction: "Tryck ut i tartform. Förgrädda med bönor i 200°C i 15 minuter.", duration: 20 },
        { order: 2, instruction: "Koka lemon curd av citronsaft, zest, ägg och socker i vattenbad.", duration: 15 },
        { order: 3, instruction: "Häll lemon curd i tartskalet. Kyl tills stelnad.", duration: 60 },
      ],
    },
    {
      title: "Saffranspannacotta",
      description: "Elegant saffranspannacotta med hjortron och en touch av kardemumma.",
      category: "dessert",
      difficulty: "easy",
      servings: 6,
      prepTime: 15,
      cookTime: 5,
      visibility: "public",
      ingredients: [
        { name: "Vispgrädde", amount: 5, unit: "dl", order: 0 },
        { name: "Socker", amount: 0.5, unit: "dl", order: 1 },
        { name: "Saffran", amount: 0.5, unit: "tsk", order: 2 },
        { name: "Gelatinblad", amount: 4, unit: "st", order: 3 },
        { name: "Kardemumma", amount: 0.5, unit: "tsk", order: 4 },
        { name: "Hjortron", amount: 150, unit: "g", order: 5 },
      ],
      steps: [
        { order: 0, instruction: "Lägg gelatinbladen i kallt vatten.", duration: 5 },
        { order: 1, instruction: "Koka upp grädde med socker, saffran och kardemumma.", duration: 5 },
        { order: 2, instruction: "Lös gelatinet i varm grädde. Häll i formar.", duration: 3 },
        { order: 3, instruction: "Kyl i 4 timmar. Servera med hjortron.", duration: 240 },
      ],
    },
  ];

  let created = 0;
  let updated = 0;
  for (const recipe of recipes) {
    const { ingredients, steps, ...recipeData } = recipe;
    const normalizedIngredients = ingredients.map((ingredient) => ({
      ...ingredient,
      unit: ingredient.unit === "st" ? "styck" : ingredient.unit,
    }));
    const totalTime = (recipeData.prepTime ?? 0) + (recipeData.cookTime ?? 0) || undefined;
    const commonData = {
      ...recipeData,
      visibility: "public" as const,
      totalTime,
    };

    const existing = await prisma.recipe.findFirst({
      where: {
        authorId: user.id,
        title: recipeData.title,
      },
      select: { id: true },
    });

    if (existing) {
      await prisma.recipe.update({
        where: { id: existing.id },
        data: {
          ...commonData,
          ingredients: {
            deleteMany: {},
            create: normalizedIngredients,
          },
          steps: {
            deleteMany: {},
            create: steps,
          },
        },
      });
      updated++;
      console.log(`↺ ${created + updated}/${recipes.length}: ${recipeData.title} (uppdaterad)`);
      continue;
    }

    await prisma.recipe.create({
      data: {
        ...commonData,
        authorId: user.id,
        ingredients: {
          create: normalizedIngredients,
        },
        steps: {
          create: steps,
        },
      },
    });
    created++;
    console.log(`✓ ${created + updated}/${recipes.length}: ${recipeData.title} (skapad)`);
  }

  console.log(`\n✅ Klart! ${created} recept skapade, ${updated} recept uppdaterade.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

